### ISSUE TITLE
loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by Huang-yihao** [vishal3477/Reverse_Engineering_GMs#3]
Hello, I have met a problem (as in the picture below) when executing the file "reverse_eng_test.py" loading the model "11_model_set_1.pickle". Could you please tell me what does the error mean? Because I am not familiar with the architecture of the model and the given pre-trained model "11_model_set_1.pickle". Upon the error is the output of the code ( print(state1['optimizer_1']) ) added by me to see the state of the "state1['optimizer_1']".  Thank you!

![image](https://user-images.githubusercontent.com/16575311/124450170-bd05ea80-ddb6-11eb-88a0-9a5634f143cf.png)

**Comment by vishal3477** [comment]
I think there is something wrong here. Can you paste the code snippet, what all you changed in code and what pretrained model you are using?

**Comment by Huang-yihao** [comment]
Thanks for your response. Below is the image (left is the original code, right is the changed code).

![image](https://user-images.githubusercontent.com/16575311/124718597-d2a31d80-df38-11eb-87ab-644e0f0c726c.png)

The model used by me is from this folder.
![image](https://user-images.githubusercontent.com/16575311/124719561-ddaa7d80-df39-11eb-8429-f411563a1e4e.png)

Could you please point out the error? Thank you very much!

**Comment by vishal3477** [comment]
Hi, 
I have made some changes in the code for fen.py in models directory. The issue is solved. Please try with the new code and let me know if any problem comes.

**Comment by Huang-yihao** [comment]
Hi, thanks for your response.  Sorry for reply so late. I have been really busy these days and I will try it as soon as possible.

**Comment by ssablak** [comment]
@vishal3477 Hi Vishal, this error is still persisted. could you please either provide a correct model or fixing the source code?

**Comment by vishal3477** [comment]
Did you try the recent commit? You can change the following line while defining the encoder: 
![image](https://user-images.githubusercontent.com/54484274/126683449-cd73b767-3d5a-4fa2-9780-3ae183ea9a20.png)

Hope this helps.

**Comment by ssablak** [comment]
@vishal3477 reverse_eng_test.py is running, but I have this error in **deepfake_detection_test.py**

Are you recommending to change in deepfake_detection_test?

```python
model_2=encoder_deepfake.encoder(num_hidden=512).to(device)
```

**Comment by ssablak** [comment]
@vishal3477 I am trying to use the following model

```python
parser.add_argument('--model_dir', default='./models/deepfake/uadfv/0_64000_model_30.pickle')
```

Actually, it gives the same error for all pre-trained deepfake models #10

**Comment by vishal3477** [comment]
Can you use the newer version of deepfake code?
